import { db } from "./db";
import { recipes } from "@shared/schema";
import { log } from "./index";

const seedRecipes = [
  {
    title: "Classic Pasta Carbonara",
    description: "A rich and creamy Italian classic made with just a few simple ingredients. The key is tempering the eggs with the hot pasta water.",
    imageUrl: "/images/carbonara.png",
    tags: ["Italian", "Pasta", "Quick"],
    ingredients: [
      "400g spaghetti",
      "200g pancetta or guanciale, diced",
      "4 large egg yolks",
      "100g Pecorino Romano, finely grated",
      "Freshly ground black pepper",
      "Salt for pasta water",
    ],
    steps: [
      "Bring a large pot of salted water to a boil and cook spaghetti until al dente",
      "While pasta cooks, fry pancetta in a large skillet over medium heat until crispy",
      "Whisk together egg yolks and grated Pecorino in a bowl",
      "Reserve 1 cup of pasta water, then drain the spaghetti",
      "Add hot pasta to the pancetta skillet, remove from heat",
      "Pour egg mixture over pasta, tossing quickly to create a creamy sauce",
      "Add pasta water a splash at a time if needed for consistency",
      "Serve immediately with extra Pecorino and black pepper",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Bolognese",
    description: "A slow-simmered Italian meat sauce made with minced meat, vegetables, wine, and tomatoes. The flavors develop through gentle cooking until rich and thick. Serve with pasta and finish with grated parmesan.",
    imageUrl: "/images/bolognese.jpg",
    tags: ["Italian", "Pasta"],
    ingredients: [
      "Butter",
      "Olive oil",
      "Basil",
      "Onions",
      "Carrot",
      "Celery",
      "Garlic",
      "Minced meat",
      "Red wine",
      "Peeled tomatoes",
      "Linguine",
      "Parmesan",
    ],
    steps: [
      "Brown the minced meat in a large pan over high heat until fully browned.",
      "Add onions, carrot, celery, and garlic to the pan.",
      "Cook until the vegetables become soft.",
      "Deglaze with a splash of red wine.",
      "Simmer until the wine is slightly reduced.",
      "Add the peeled tomatoes.",
      "Season with salt, pepper, and basil.",
      "Simmer on low heat for 30–45 minutes until thick and rich.",
      "Cook the linguine according to the package instructions.",
      "Mix the sauce with the cooked pasta.",
      "Sprinkle with parmesan before serving.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Hawaiian Poke Bowl",
    description: "A vibrant and healthy bowl packed with fresh flavors. This Hawaiian staple is perfect for a light yet satisfying meal.",
    imageUrl: "/images/poke-bowl.png",
    tags: ["Hawaiian", "Healthy", "Seafood"],
    ingredients: [
      "300g sushi-grade ahi tuna, cubed",
      "2 cups cooked sushi rice",
      "1 ripe avocado, sliced",
      "1/2 cup shelled edamame",
      "1/4 cup soy sauce",
      "1 tsp sesame oil",
      "1 mango, diced",
      "Sesame seeds and scallions for garnish",
      "Pickled ginger (optional)",
    ],
    steps: [
      "Marinate tuna cubes in soy sauce and sesame oil for 15 minutes",
      "Cook sushi rice according to package directions and let cool slightly",
      "Divide rice between two bowls",
      "Arrange marinated tuna, avocado, edamame, and mango on top",
      "Sprinkle with sesame seeds and sliced scallions",
      "Serve with pickled ginger on the side",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Fluffy Blueberry Pancakes",
    description: "Golden, pillowy pancakes bursting with fresh blueberries. A perfect weekend breakfast that the whole family will love.",
    imageUrl: "/images/pancakes.png",
    tags: ["Breakfast", "Sweet", "Family"],
    ingredients: [
      "1 1/2 cups all-purpose flour",
      "3 1/2 tsp baking powder",
      "1 tbsp sugar",
      "1/4 tsp salt",
      "1 1/4 cups milk",
      "1 egg",
      "3 tbsp melted butter",
      "1 cup fresh blueberries",
      "Maple syrup for serving",
    ],
    steps: [
      "Whisk together flour, baking powder, sugar, and salt in a large bowl",
      "Make a well in the center and pour in milk, egg, and melted butter",
      "Mix until smooth but don't overmix - a few lumps are fine",
      "Gently fold in fresh blueberries",
      "Heat a lightly oiled griddle or pan over medium-high heat",
      "Pour about 1/4 cup batter per pancake onto the griddle",
      "Cook until bubbles form on the surface, then flip and cook until golden",
      "Stack pancakes and serve with butter and warm maple syrup",
    ],
    createdByUserId: "seed",
    isBase: true,
  },

    {
    title: "Pizza",
    description: "A simple homemade pizza dough made in a mixer and left to rise for 2 hours. The amount is intended for 6 people. Top with tomato sauce, mozzarella, and parmesan and bake until golden.",
    imageUrl: "/images/pizza.jpg",
    tags: ["Italian"],
    ingredients: [
      "600g flour",
      "300ml water",
      "Olive oil",
      "Yeast",
      "Salt",
      "Sugar",
      "Tomato sauce",
      "Mozzarella",
      "Parmesan",
    ],
    steps: [
      "Make the dough in a mixer.",
      "Let the dough rise for 2 hours.",
      "Shape the dough into pizza bases.",
      "Spread tomato sauce over the bases.",
      "Top with mozzarella and parmesan.",
      "Bake until the crust is cooked and lightly browned.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Mushroom Ragout",
    description: "A hearty mushroom ragout thickened with tomatoes and enriched with toasted walnuts. Dried porcini add depth, while herbs bring a savory aroma. Toss with pasta and finish with fresh parsley.",
    imageUrl: "/images/pilz-ragout.jpg",
    tags: ["Vegetarian", "Pasta"],
    ingredients: [
      "1 can chopped tomatoes",
      "400 g button mushrooms",
      "100 g walnuts",
      "20 g porcini, dried",
      "Pasta",
      "2 celery stalks",
      "2 garlic cloves",
      "1 onion",
      "1 handful fresh parsley",
      "2 tbsp tamari",
      "1 tbsp tomato paste",
      "1 tsp thyme, dried",
      "1 tsp oregano, dried",
      "1 tsp rosemary",
      "Salt",
      "Pepper",
      "Olive oil",
    ],
    steps: [
      "Pour 250 ml boiling water over the dried porcini and soak for 20 minutes.",
      "Drain the porcini, reserving the soaking liquid.",
      "Chop the soaked porcini into small pieces.",
      "Finely chop the walnuts until they resemble coarse breadcrumbs.",
      "Toast the walnuts in a large deep pan over medium heat for about 5 minutes, stirring occasionally.",
      "Remove the toasted walnuts from the pan and set aside.",
      "Add onion, garlic, and celery to the pan with olive oil and a pinch of salt.",
      "Fry for 5–10 minutes until softened.",
      "Add fresh mushrooms and diced pepper, then add thyme, oregano, and rosemary.",
      "Cook for about 5 minutes until softened.",
      "Add the canned tomatoes and tomato paste to the pan.",
      "Add the tamari, the soaked porcini, and the reserved soaking liquid.",
      "Simmer for 10–15 minutes until the ragout thickens and excess liquid cooks off.",
      "Stir in the toasted walnuts and nutritional yeast.",
      "Simmer for 5 more minutes.",
      "Cook the pasta in boiling salted water according to the package instructions.",
      "Drain the pasta well.",
      "Stir the pasta into the finished ragout.",
      "Sprinkle with chopped parsley before serving.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Spinach Pasta",
    description: "Creamy pasta with sun-dried tomatoes, parmesan, and baby spinach. The sauce comes together quickly with cream and vegetable stock. A fast vegetarian meal for busy days.",
    imageUrl: "/images/Pasta_Spinat-Sahne-Sauce.jpg",
    tags: ["Pasta", "Vegetarian"],
    ingredients: [
      "300 g pasta",
      "1 onion",
      "2 garlic cloves",
      "1 tbsp olive oil",
      "100 g sun-dried tomatoes (from a jar)",
      "250 g cooking cream",
      "200 ml vegetable stock",
      "60 g grated parmesan",
      "100 g baby spinach",
      "Salt and pepper",
      "1 tsp Italian herbs",
    ],
    steps: [
      "Cook the pasta according to the package instructions.",
      "Finely chop the onion and garlic.",
      "Heat olive oil in a pan.",
      "Fry the onion and garlic for 2 minutes.",
      "Add the cream and vegetable stock.",
      "Bring the sauce to a boil.",
      "Stir in the parmesan, sun-dried tomatoes, and baby spinach.",
      "Simmer for 5 minutes over medium heat.",
      "Season with salt, pepper, and Italian herbs.",
      "Stir the cooked pasta into the sauce.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Penne Arrabbiata",
    description: "Spicy Italian penne in a simple tomato sauce with garlic, chili, and herbs. The sauce simmers until rich and aromatic. Finish with parmesan if you like.",
    imageUrl: "/images/penne_arrabiata.jpg",
    tags: ["Pasta", "Italian", "Spicy"],
    ingredients: [
      "400 g penne",
      "1 can tomatoes",
      "2 tbsp olive oil",
      "4 garlic cloves",
      "1 bunch basil",
      "3 red chili peppers",
      "1 pinch pepper",
      "1 pinch salt",
      "1 sprig oregano",
      "Parmesan",
    ],
    steps: [
      "Cook the penne in salted water until al dente.",
      "Drain the pasta and let it drip off well.",
      "Peel and finely chop the garlic.",
      "Wash the basil, drain it, and finely chop it.",
      "Wash the chili peppers, remove the seeds, and chop them.",
      "Gently sauté garlic and chili in a pan with olive oil.",
      "Add the tomatoes to the pan.",
      "Simmer the sauce for 15 minutes.",
      "Add a little pasta water to the sauce.",
      "Add the drained penne to the pan.",
      "Stir in basil and oregano.",
      "Season with salt and pepper to taste.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Mozzarella Pasta",
    description: "Pasta tossed with a fresh tomato sauce, herbs, and melty mozzarella. A splash of white wine adds brightness to the sauce. Finish with fresh basil for a classic Italian feel.",
    imageUrl: "/images/mozzarella-tomatensauce.jpg",
    tags: ["Pasta", "Italian", "Vegetarian"],
    ingredients: [
      "350 g pasta",
      "Bunch fresh basil",
      "250 g mozzarella",
      "3 tbsp olive oil",
      "2 tsp sugar",
      "1 tsp dried oregano",
      "1 splash white wine",
      "1 pinch salt",
      "1 pinch pepper",
      "1 tbsp oil for the pan",
      "500 g passata",
      "250 g cherry tomatoes",
    ],
    steps: [
      "Cook the pasta in salted water until al dente.",
      "Peel and finely chop the onion and garlic.",
      "Heat oil in a pan and sauté the onion and garlic.",
      "Wash the cherry tomatoes and remove the seeds.",
      "Dice the tomatoes very finely.",
      "Add the diced tomatoes to the pan and sauté briefly.",
      "Deglaze with a splash of white wine.",
      "Pour in the passata.",
      "Season with salt, pepper, sugar, olive oil, and oregano.",
      "Let the sauce simmer briefly.",
      "Cut the mozzarella into small pieces.",
      "Mix pasta, mozzarella, basil leaves, and tomato sauce together.",
      "Serve immediately.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Baked Feta Pasta",
    description: "Oven-baked feta and tomatoes turn into a creamy sauce with almost no effort. Herbs and garlic add a savory kick as everything roasts together. Toss with pasta and serve hot with parsley.",
    imageUrl: "/images/feta-pasta.jpg",
    tags: ["Pasta", "Vegetarian"],
    ingredients: [
      "300 g feta",
      "700 g cherry tomatoes",
      "2 garlic cloves",
      "1 tbsp olive oil",
      "0.5 bunch parsley",
      "1 tsp dried thyme",
      "500 g pasta",
      "Salt",
      "Pepper",
    ],
    steps: [
      "Preheat the oven to 200°C top/bottom heat.",
      "Add tomatoes and garlic to a large baking dish.",
      "Add half of the parsley and mix everything together.",
      "Place the feta in the center of the baking dish.",
      "Sprinkle the remaining thyme over the feta.",
      "Season with salt and pepper.",
      "Drizzle with olive oil.",
      "Bake for about 30 minutes.",
      "Cook the pasta al dente according to the package instructions.",
      "Remove the baking dish from the oven.",
      "Mix the baked feta with the tomatoes until creamy.",
      "Drain the pasta.",
      "Add the pasta to the sauce and mix well.",
      "Garnish with the remaining parsley and serve hot.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Pepper Pasta",
    description: "Creamy pasta sauce made from roasted red peppers blended smooth with garlic and onion. Roasting adds sweetness and depth while keeping the recipe simple. Toss with pasta and finish with parmesan.",
    imageUrl: "/images/paprikasauce.jpg",
    tags: ["Vegetarian", "Pasta"],
    ingredients: [
      "250 g pasta of choice",
      "1 onion",
      "3-4 garlic cloves",
      "2 red peppers",
      "1 tbsp oil",
      "2 tbsp tomato paste",
      "3-4 tbsp parmesan",
      "⅔ tsp salt",
      "Hot paprika powder, pepper, or chili to taste",
    ],
    steps: [
      "Preheat the oven to 220°C top/bottom heat.",
      "Peel the onion and garlic.",
      "Quarter the onion and leave the garlic whole.",
      "Halve the peppers, remove seeds, wash, and cut into strips.",
      "Place peppers, onion, and garlic on a baking tray.",
      "Drizzle with oil.",
      "Roast for about 20 minutes.",
      "Cook the pasta al dente and drain.",
      "Blend the roasted vegetables with tomato paste and salt until creamy.",
      "Season with hot paprika powder, pepper, or chili.",
      "Bring the pepper sauce to a brief boil in a pot.",
      "Adjust seasoning and thin with water if needed.",
      "Add the pasta to the sauce and mix well.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Mushroom Pasta",
    description: "Creamy mushroom pasta with garlic, onions, and a quick pan sauce. A splash of white wine is optional but adds extra aroma. Serve with parmesan and fresh herbs.",
    imageUrl: "/images/pilzsahne.jpg",
    tags: ["Vegetarian", "Pasta"],
    ingredients: [
      "300 g pasta",
      "2 tbsp rapeseed oil or olive oil",
      "1 onion, chopped",
      "4 garlic cloves, chopped",
      "500 g button mushrooms, sliced",
      "80 ml dry white wine (optional)",
      "360 ml vegetable stock",
      "3 tbsp flour",
      "Salt and pepper to taste",
    ],
    steps: [
      "Cook the pasta al dente in salted water according to the package instructions.",
      "Drain the pasta.",
      "Heat 1 tbsp oil in a pan.",
      "Fry the onion for about 3 minutes.",
      "Add the remaining oil, garlic, and mushrooms.",
      "Fry for 5–7 minutes until the mushrooms are browned.",
      "Deglaze with white wine if using.",
      "Let the wine evaporate briefly.",
      "Mix vegetable stock, cream, and flour together.",
      "Pour the mixture into the pan.",
      "Simmer for 5–10 minutes until the sauce reaches the desired thickness.",
      "Season with paprika powder, salt, and pepper.",
      "Stir the pasta into the sauce.",
      "Serve with parmesan and fresh herbs.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Zucchini Ricotta Pasta",
    description: "A creamy pasta dish where zucchini is gently cooked and mixed into a ricotta cheese cream. Parmesan, pecorino, and nutmeg add richness and depth. Toss with pasta and brighten with a little lemon.",
    imageUrl: "/images/zucchini_ricotta_pasta.jpg",
    tags: ["Pasta", "Vegetarian"],
    ingredients: [
      "400 g fusilli or another short pasta shape",
      "400 g zucchini",
      "100 g ricotta",
      "25 g pecorino",
      "25 g parmesan",
      "1/2 tsp nutmeg",
      "4 tbsp olive oil",
      "2 garlic cloves",
      "10 basil leaves",
      "Salt",
      "Freshly ground black pepper",
      "Lemon",
    ],
    steps: [
      "Cook the pasta in salted water according to the package instructions.",
      "Dice the zucchini.",
      "Roughly chop the basil.",
      "Finely chop the garlic.",
      "Heat olive oil in a pan and warm the garlic briefly.",
      "Add zucchini and basil to the pan.",
      "Season with salt.",
      "Cover and cook on low heat for 15–20 minutes, stirring occasionally.",
      "Add a little warm water if the zucchini starts to stick.",
      "Mash the cooked zucchini.",
      "Stir the ricotta in a large bowl until creamy.",
      "Mix in parmesan, pecorino, and nutmeg.",
      "Add the mashed zucchini to the bowl.",
      "Add 3–4 tbsp pasta water and mix well.",
      "Add the hot drained pasta to the cream and mix thoroughly.",
      "Season with salt and black pepper to taste.",
      "Serve and add lemon as desired.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Lemon Zoodles Pasta",
    description: "A bright lemon pasta mixed with quickly sautéed zucchini noodles and a creamy cashew-lemon sauce. Basil and garlic add freshness and aroma. A satisfying vegetarian dish with a light, zesty finish.",
    imageUrl: "/images/lemon_zoodles_pasta.jpg",
    tags: ["Pasta", "Vegetarian"],
    ingredients: [
      "3 tbsp cashews",
      "200 ml water",
      "250 g spaghetti",
      "2 tbsp and 1/2 tsp salt",
      "4 garlic cloves",
      "2 zucchini",
      "1 untreated organic lemon",
      "Black pepper",
      "about 30 basil leaves",
      "2 tbsp nutritional yeast",
      "about 200 g cooked white beans",
      "3 tbsp olive oil",
      "Dried chili (optional)",
    ],
    steps: [
      "Soak the cashews in hot water.",
      "Cook the spaghetti al dente in salted water.",
      "Finely chop the garlic.",
      "Spiralize the zucchini into zoodles and shorten them if needed.",
      "Grate the lemon zest and squeeze the lemon juice.",
      "Blend lemon zest and juice with cashews, water, salt, pepper, basil, nutritional yeast, and white beans until creamy.",
      "Heat olive oil in a pan.",
      "Briefly fry dried chili and garlic.",
      "Add the zoodles and sauté very briefly.",
      "Add the spaghetti to the pan.",
      "Add the lemon-cashew sauce and mix everything together.",
      "Garnish with lemon zest and basil and serve.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
    {
    title: "Olive Caper Pasta",
    description: "A quick tomato paste sauce with shallots, garlic, olives, and capers. Basil adds freshness and the sauce comes together in minutes. Toss with pasta and finish with extra basil.",
    imageUrl: "/images/pasta_tomatensauce_oliven_kapern.jpg",
    tags: ["Pasta", "Vegetarian"],
    ingredients: [
      "500 g pasta",
      "4 shallots",
      "2 garlic cloves",
      "60 g green olives",
      "2 tbsp capers",
      "200 g tomato paste",
      "160 ml water",
      "3 sprigs basil",
      "Pepper",
      "1 tsp salt",
      "1 tbsp olive oil",
    ],
    steps: [
      "Bring salted water to a boil.",
      "Cook the pasta until al dente according to the package instructions.",
      "Peel and finely chop the shallots and garlic.",
      "Heat olive oil in a pan.",
      "Sauté the shallots and garlic in the pan.",
      "Add the tomato paste and fry briefly.",
      "Deglaze with water.",
      "Chop the olives and capers.",
      "Chop the basil leaves.",
      "Add olives, capers, and basil to the sauce.",
      "Simmer the sauce for about 5 minutes.",
      "Season with salt and pepper.",
      "Drain the pasta.",
      "Toss the pasta with the sauce.",
      "Serve with fresh basil leaves.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Tuna Lemon Pasta",
    description: "A light tuna pasta with lemon zest, capers, and fresh parsley. Tomatoes add freshness and cream rounds out the sauce. Quick to make and bright in flavor.",
    imageUrl: "/images/pasta_tuna_lemon_capers.jpg",
    tags: ["Pasta", "Seafood"],
    ingredients: [
      "2 small onions",
      "1 can tuna in its own juice",
      "1 lemon, zest and juice",
      "2 tbsp capers",
      "½ bunch parsley",
      "50 g butter",
      "¼ cup cream",
      "Salt and pepper",
      "200 g spaghetti",
      "2 tomatoes",
    ],
    steps: [
      "Finely chop the onions.",
      "Drain the tuna and break it into small pieces.",
      "Wash and dry the lemon, then grate the zest.",
      "Juice the lemon.",
      "Rinse the capers.",
      "Finely chop the parsley.",
      "Peel and dice the tomatoes.",
      "Cook the spaghetti in salted water according to the package instructions.",
      "Melt the butter in a pan.",
      "Sauté the onions with the lemon zest.",
      "Add the tuna and capers and fry briefly.",
      "Pour in the lemon juice.",
      "Add the diced tomatoes and let the liquid evaporate slightly.",
      "Stir in the cream.",
      "Season with salt and pepper.",
      "Stir in the parsley and remove from heat.",
      "Drain the pasta while still al dente.",
      "Serve the pasta with the sauce.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Tuna Tomato Pasta",
    description: "A simple tuna tomato sauce with onion, garlic, and passata. Tomato paste and oregano add depth and aroma. Toss with pasta for an easy weeknight meal.",
    imageUrl: "/images/pasta_tuna_tomato_sauce.jpg",
    tags: ["Pasta", "Seafood"],
    ingredients: [
      "2 cans tuna",
      "1 can passata",
      "1 onion",
      "2 garlic cloves",
      "2 tbsp oil",
      "1 pinch pepper",
      "1 pinch salt",
      "1 tsp tomato paste",
      "1 pinch dried oregano",
      "1 splash olive oil",
      "Pasta",
    ],
    steps: [
      "Cook the pasta according to the package instructions.",
      "Peel and finely chop the onion and garlic.",
      "Heat the oil in a pan.",
      "Sauté the onion and garlic in the pan.",
      "Add the passata.",
      "Add the tuna.",
      "Bring the sauce to a boil.",
      "Season with salt, pepper, tomato paste, and dried oregano.",
      "Add a splash of olive oil.",
      "Serve the pasta with the tuna tomato sauce.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Cacio e Pepe",
    description: "A classic Roman pasta with pecorino and black pepper. The creamy sauce is created by mixing cheese with starchy pasta water. Simple ingredients, big flavor.",
    imageUrl: "/images/spaghetti_cacio_e_pepe.jpg",
    tags: ["Pasta", "Italian", "Vegetarian"],
    ingredients: [
      "300 g spaghetti",
      "200 g Pecorino Romano",
      "1 tsp black pepper",
      "2 ½ liters water",
      "Salt",
    ],
    steps: [
      "Bring 2.5 liters of water to a boil and salt it.",
      "Cook the spaghetti until al dente.",
      "Heat a large pan over medium heat.",
      "Crush or grind the black pepper.",
      "Toast the pepper in the dry pan without burning it.",
      "Add 1 cup of pasta water to the pan to stop the pepper from burning.",
      "Finely grate the Pecorino into a bowl.",
      "Add a few tablespoons of hot pasta water to the Pecorino.",
      "Stir until a smooth cheese cream forms.",
      "When the pasta has 3 minutes left, add another ladle of pasta water to the pan.",
      "Transfer the spaghetti from the pot into the pan.",
      "Finish cooking the spaghetti in the pan with minimal liquid, stirring often.",
      "Add the Pecorino cream to the pan.",
      "Stir and toss until a creamy sauce forms.",
      "Add small amounts of pasta water as needed to perfect the sauce consistency.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Carbonara",
    description: "A classic carbonara made with crispy pancetta, eggs, and two cheeses. Hot pasta and a little pasta water create a silky sauce without cream. Serve immediately with plenty of black pepper.",
    imageUrl: "/images/carbonara.jpg",
    tags: ["Pasta", "Italian", "Vegetarian"],
    ingredients: [
      "240 g long thin pasta",
      "100 g pancetta, guanciale, or raw Italian ham",
      "2 eggs",
      "40 g parmesan or Grana Padano, freshly grated",
      "40 g Pecorino Romano, freshly grated",
      "Olive oil",
      "Salt and freshly ground black pepper",
    ],
    steps: [
      "Dice the pancetta or ham into larger pieces.",
      "Heat olive oil in a pan.",
      "Sauté the pancetta until lightly cooked, then set aside.",
      "Cook the pasta in plenty of salted water until al dente.",
      "Reserve 1–2 small cups of pasta water near the end of cooking.",
      "Whisk the eggs with parmesan and Pecorino in a bowl.",
      "Season the egg mixture lightly with salt and black pepper.",
      "Reheat the pancetta in the pan.",
      "Add the reserved pasta water and bring it to a boil.",
      "Add the drained pasta to the pan and stir.",
      "Add the egg and cheese mixture.",
      "Let it thicken slightly while stirring constantly to coat the pasta.",
      "Serve immediately.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Lasagna",
    description: "Classic baked lasagna layered with a meat ragu and a smooth béchamel sauce. The top is finished with cheese and butter for a golden crust. Bake until bubbling and deeply browned.",
    imageUrl: "/images/lasagna.jpg",
    tags: ["Italian", "Pasta"],
    ingredients: [
      "Olive oil",
      "500 g mixed minced meat",
      "1 onion",
      "2 garlic cloves",
      "1 bunch parsley (or frozen)",
      "1 tbsp tomato paste",
      "1 can peeled tomatoes (800 g)",
      "Some red wine",
      "½ liter milk",
      "30 g butter",
      "40 g flour",
      "Salt and pepper",
      "Lemon juice",
      "Nutmeg",
      "Butter for the dish",
      "300 g lasagna sheets",
      "Grated cheese, to taste",
      "Butter flakes",
    ],
    steps: [
      "Heat olive oil in a pot.",
      "Brown the minced meat all over.",
      "Add chopped onion and parsley and cook briefly.",
      "Add sliced garlic and tomato paste and fry briefly.",
      "Add the canned tomatoes.",
      "Season the ragu with salt and pepper.",
      "Add red wine if desired.",
      "Simmer the ragu uncovered for at least 30 minutes.",
      "Melt butter in a small pot for the béchamel.",
      "Whisk in the flour and cook until pale golden.",
      "Pour in the milk and whisk until smooth.",
      "Strain the sauce if needed to remove lumps.",
      "Simmer the béchamel on low heat for about 30 minutes.",
      "Season the béchamel with salt, pepper, lemon juice, and nutmeg.",
      "Preheat the oven to 180°C fan.",
      "Butter an ovenproof baking dish.",
      "Spread a thin layer of ragu in the dish.",
      "Add a layer of lasagna sheets.",
      "Cover with ragu and then a layer of béchamel.",
      "Repeat layers, finishing with béchamel on top.",
      "Sprinkle generously with grated cheese.",
      "Dot the top with butter flakes.",
      "Bake for 30–40 minutes until the crust is golden brown.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Vegetable Pasta Bake",
    description: "A hearty pasta bake with a tomato-vegetable sauce and melted gouda on top. The vegetables simmer until tender, then everything is baked until golden. Great for feeding a crowd.",
    imageUrl: "/images/vegetable_pasta_bake.jpg",
    tags: ["Vegetarian", "Pasta"],
    ingredients: [
      "2 onions",
      "2 carrots",
      "1 zucchini",
      "1 bell pepper",
      "1 garlic clove",
      "100 ml vegetable stock",
      "500 ml passata",
      "3 tbsp tomato paste",
      "2 tsp paprika powder",
      "Some basil (fresh or dried)",
      "Some oregano",
      "Salt and pepper",
      "500 g fusilli",
      "Olive oil",
      "200 g grated gouda",
    ],
    steps: [
      "Dice the onions, carrots, zucchini, and bell pepper.",
      "Cook the fusilli in salted water until al dente.",
      "Drain the pasta and leave it in the pot.",
      "Heat olive oil in a deep pan.",
      "Sauté the onions until translucent.",
      "Press the garlic and add it to the pan.",
      "Add the remaining diced vegetables.",
      "Add tomato paste, paprika powder, basil, and oregano.",
      "Fry briefly to release aromas.",
      "Deglaze with vegetable stock.",
      "Simmer on low heat for about 15 minutes.",
      "Add the passata.",
      "Season with salt and pepper.",
      "Bring the sauce to a brief boil.",
      "Pour the sauce over the pasta and mix.",
      "Transfer the mixture to a baking dish.",
      "Sprinkle with grated gouda.",
      "Bake at 220°C for 20–30 minutes until browned to your liking.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Spinach Tortellini",
    description: "Homemade tortellini filled with spinach and ricotta, finished with parmesan and melted butter. The pasta dough is rested, rolled thin, and shaped by hand. A classic, delicate pasta dish.",
    imageUrl: "/images/tortellini_spinach_cheese.jpg",
    tags: ["Pasta", "Vegetarian", "Italian"],
    ingredients: [
      "80 g parmesan",
      "60 g ricotta or cottage cheese",
      "5 egg yolks",
      "40 g butter, for drizzling",
      "70 g leaf spinach",
      "1 pinch nutmeg",
      "1 pinch pepper",
      "1 pinch salt",
      "1 egg for the dough",
      "150 g flour",
      "1 splash olive oil",
      "1 pinch salt for the dough",
      "1 egg yolk for the dough",
    ],
    steps: [
      "Knead flour, egg yolk, salt, 1 egg, and olive oil into a smooth dough.",
      "Cover the dough and let it rest for 30 minutes.",
      "Blanch the spinach briefly.",
      "Squeeze out the spinach well.",
      "Finely chop the spinach.",
      "Press the ricotta through a sieve into a bowl.",
      "Mix ricotta with spinach and 50 g grated parmesan.",
      "Season the filling with salt, pepper, and nutmeg.",
      "Roll the dough out thinly.",
      "Cut out 8 dough circles about 10 cm in diameter.",
      "Place filling onto each circle and make an indentation in the center.",
      "Separate the eggs and place one yolk into each indentation.",
      "Brush the edges with egg white.",
      "Fold each circle into a triangle and press the edges firmly to seal.",
      "Fold the rounded side up toward the triangle tip.",
      "Wrap the ends around your finger, moisten, and pinch together.",
      "Cook the tortellini in salted water for 3–5 minutes.",
      "Drain well.",
      "Sprinkle with parmesan.",
      "Drizzle with melted butter and serve.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Thai Peanut Ramen",
    description: "Creamy, spicy ramen with coconut milk and peanut butter in a Thai-style broth. Crispy tofu and sautéed mushrooms make it hearty and satisfying. Finish with toppings like scallions and roasted peanuts.",
    imageUrl: "/images/ramen.jpg",
    tags: ["Asian", "Vegetarian", "Soup"],
    ingredients: [
      "2 tsp coconut oil",
      "2 garlic cloves, finely chopped",
      "1 tsp ginger, finely grated",
      "1 tbsp Thai curry paste",
      "3-4 cups vegetable broth",
      "1 can coconut milk, 400ml",
      "80 g peanut butter",
      "2 tbsp soy sauce or tamari",
      "1 tbsp agave syrup",
      "1 tsp Knorr jalapeño seasoning",
      "250 g ramen noodles",
      "300 g tofu, cubed",
      "2 tsp cornstarch",
      "1/2 tsp turmeric",
      "2 tbsp peanut oil",
      "350 g button mushrooms, sliced",
      "1 tbsp soy sauce",
      "Optional: roasted peanuts, sesame, scallions",
    ],
    steps: [
      "Heat coconut oil in a large pot.",
      "Sauté the garlic and ginger.",
      "Add the Thai curry paste and fry briefly.",
      "Add coconut milk and vegetable broth.",
      "Bring the broth to a boil.",
      "Stir in peanut butter, soy sauce, agave syrup, and jalapeño seasoning.",
      "Simmer the broth for about 10 minutes.",
      "Add the ramen noodles.",
      "Cook according to the package instructions.",
      "Drain the tofu well.",
      "Coat the tofu with turmeric and cornstarch.",
      "Heat peanut oil in a pan.",
      "Fry the tofu until crispy.",
      "In a separate pan, sauté the mushrooms until browned.",
      "Deglaze the mushrooms with soy sauce.",
      "Serve the ramen with crispy tofu and mushrooms.",
      "Add toppings like scallions and roasted peanuts if desired.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Mushroom Risotto",
    description: "Creamy mushroom risotto finished with butter and parmesan. Shallots and garlic build the base, while wine and broth create a rich, velvety texture. Serve with parsley and freshly ground pepper.",
    imageUrl: "/images/pilzrisotto.jpg",
    tags: ["Italian", "Vegetarian", "Rice"],
    ingredients: [
      "300 g mixed mushrooms (button mushrooms, chanterelles, porcini)",
      "200 g risotto rice",
      "2 shallots",
      "1 bunch parsley",
      "1 garlic clove",
      "40 g butter",
      "100 ml white wine",
      "400 ml chicken broth",
      "50 g parmesan, freshly grated",
      "Olive oil",
      "Salt",
      "White pepper, freshly ground",
      "Nutmeg",
      "Parmesan",
    ],
    steps: [
      "Finely chop the shallots and garlic.",
      "Melt some butter in a pot and sauté the shallots and garlic.",
      "Add the risotto rice and sauté briefly.",
      "Deglaze with white wine.",
      "Add broth and bring to a simmer.",
      "Cook the rice for about 12 minutes, stirring regularly.",
      "Remove the pot from the heat.",
      "Stir in the remaining butter and parmesan.",
      "Sauté the mushrooms with shallot in a separate pan.",
      "Fold the cooked mushrooms into the risotto.",
      "Season with salt, nutmeg, and white pepper.",
      "Sprinkle with parsley before serving.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Pad Thai",
    description: "A classic stir-fried rice noodle dish with tofu, shrimp, egg, and a savory-sweet sauce. Finished with bean sprouts, spring onions, peanuts, and lime. Fast, fragrant, and satisfying.",
    imageUrl: "/images/pad-thai.jpg",
    tags: ["Asian", "Vegetarian"],
    ingredients: [
      "100 g rice noodles, 3 mm wide",
      "100 g tofu",
      "100 g shrimp",
      "4 garlic cloves",
      "2 spring onions",
      "100 g bean sprouts",
      "2 eggs",
      "2 tbsp neutral vegetable oil (e.g., sunflower oil)",
      "2 tsp brown sugar",
      "4 tsp fish sauce",
      "6 tsp oyster sauce",
      "1 cup water",
      "Peanuts, unsalted, roasted",
      "Chili flakes",
      "1 lime",
      "Turmeric powder",
    ],
    steps: [
      "Soak the rice noodles in hot water until softened.",
      "Rub the tofu with turmeric powder.",
      "Cut the tofu into pieces.",
      "Finely chop the garlic.",
      "Cut the spring onions into 2 cm pieces.",
      "Wash the bean sprouts.",
      "Chop the peanuts.",
      "Heat oil in a wok.",
      "Briefly fry the garlic.",
      "Add shrimp and tofu and stir-fry.",
      "Add the eggs and stir.",
      "Add fish sauce, brown sugar, and oyster sauce.",
      "Stir until everything is well mixed.",
      "Add water and the soaked noodles.",
      "Add bean sprouts and spring onions.",
      "Cook briefly until warmed through.",
      "Serve with chopped peanuts, chili flakes, and lime.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Avocado Pea Pasta",
    description: "Creamy avocado pasta blended with peas, lemon, basil, and garlic. Quick to make and fresh in flavor with a bright citrus finish. Top with a little lemon zest before serving.",
    imageUrl: "/images/erbsen-avocado.jpg",
    tags: ["Vegan", "Vegetarian", "Pasta"],
    ingredients: [
      "2 handfuls organic fusilli",
      "1 handful organic young peas",
      "1 organic avocado",
      "1 organic lemon",
      "1 organic garlic clove",
      "Organic olive oil",
      "Organic basil",
      "Salt",
      "Pepper",
    ],
    steps: [
      "Bring a pot of water to a boil.",
      "Halve the avocado and remove the pit.",
      "Scoop the avocado flesh into a small bowl.",
      "Halve the lemon and squeeze the juice of one half over the avocado.",
      "Mash the avocado into a smooth cream with a fork.",
      "Peel and finely chop the garlic.",
      "Finely chop a few basil leaves.",
      "Add garlic and basil to the avocado cream.",
      "Season with a splash of olive oil, salt, and pepper.",
      "Salt the boiling water.",
      "Cook the fusilli until al dente.",
      "Drain the peas.",
      "Blend the peas with the avocado cream until smooth.",
      "Add the sauce to the pot with the pasta.",
      "Mix well to coat the pasta.",
      "Grate a little lemon zest over the plated pasta.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Spinach Cannelloni",
    description: "Baked cannelloni filled with ricotta and spinach, layered with béchamel and basil tomato sauce. Topped with Parmigiano Reggiano and baked until golden. A comforting Italian oven dish.",
    imageUrl: "/images/cannelloni_ricotta_spinat.jpg",
    tags: ["Italian", "Vegetarian", "Pasta", "Oven-baked"],
    ingredients: [
      "20 g parmesan, grated",
      "250 g cannelloni",
      "400 g spinach",
      "300 g ricotta",
      "1 tbsp olive oil",
      "100 g Parmigiano Reggiano, grated",
      "1 pinch salt",
      "1 pinch pepper",
      "1 tbsp butter",
      "200 ml Barilla Basilico sauce",
      "10 g basil",
      "40 g butter (for the béchamel)",
      "40 g flour (for the béchamel)",
      "750 ml milk (for the béchamel)",
      "4 g nutmeg (for the béchamel)",
    ],
    steps: [
      "Melt 40 g butter in a small pot for the béchamel.",
      "Whisk in 40 g flour and cook briefly.",
      "Heat the milk with nutmeg.",
      "Gradually whisk the milk into the roux until smooth.",
      "Season the béchamel with salt and simmer for a few minutes while stirring.",
      "Wash and drain the spinach.",
      "Heat olive oil in a pot.",
      "Wilt the spinach over high heat.",
      "Let the spinach cool, squeeze it well, and finely chop it.",
      "Mash the ricotta in a bowl.",
      "Mix in the chopped spinach.",
      "Add an egg yolk and half of the Parmigiano Reggiano.",
      "Season the filling with salt and pepper and mix until smooth.",
      "Preheat the oven to 180°C.",
      "Butter a baking dish.",
      "Spread a thin layer of béchamel and a little basil tomato sauce in the dish.",
      "Fill the cannelloni with the spinach-ricotta mixture.",
      "Place the filled cannelloni in the dish.",
      "Cover with béchamel sauce.",
      "Add the remaining basil tomato sauce on top.",
      "Sprinkle with the remaining Parmigiano Reggiano.",
      "Bake for 40 minutes.",
      "Serve with basil leaves and a drizzle of olive oil.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Pumpkin Sauerkraut Pasta",
    description: "A cozy one-pan pasta with pumpkin and sauerkraut, finished with melted mountain cheese. Noodle water helps create a light sauce while everything simmers together. Savory, tangy, and comforting.",
    imageUrl: "/images/schupfnudeln_sauerkraut_kuerbis.jpg",
    tags: ["Vegetarian", "Pasta"],
    ingredients: [
      "240 g ribbon noodles",
      "300 g pumpkin flesh",
      "380 g sauerkraut",
      "2 tbsp rapeseed oil",
      "100 g mountain cheese, grated",
      "2 tbsp flat-leaf parsley",
      "Nutmeg",
      "Salt",
    ],
    steps: [
      "Cook the ribbon noodles until al dente according to the package instructions.",
      "Cut the pumpkin into large cubes.",
      "Heat rapeseed oil in a pan over medium heat.",
      "Fry the pumpkin and sauerkraut for 3 minutes.",
      "Deglaze with 2 cups of pasta water.",
      "Cook for 7 minutes, stirring occasionally.",
      "Add the cooked noodles to the pan.",
      "Stir in two thirds of the cheese.",
      "Stir in the parsley.",
      "Season with nutmeg and salt.",
      "Sprinkle the remaining cheese and parsley on top.",
      "Cover the pan and melt the cheese on the lowest heat for 3 minutes.",
      "Serve immediately.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Homemade Spinach Pasta",
    description: "Quick homemade spinach pasta made from thawed spinach, flour, and salt. The dough is shaped into strands and cut into small pieces that cook right in simmering water. Serve with green pesto, parmesan, and basil.",
    imageUrl: "/images/spinatnudeln.jpg",
    tags: ["Vegetarian", "Pasta"],
    ingredients: [
      "300 g leaf spinach, frozen",
      "300 g wheat flour",
      "1 tsp salt",
      "Green pesto",
      "Parmesan, grated",
      "Fresh basil leaves",
    ],
    steps: [
      "Place the frozen spinach in a sieve and let it thaw for about 30 minutes.",
      "Squeeze the thawed spinach very well.",
      "Put the spinach into a pot and chop it up.",
      "Add wheat flour and salt.",
      "Knead into a dough.",
      "Knead the dough briefly on a floured surface.",
      "Divide the dough into 4 equal portions.",
      "Roll each portion into a dough rope.",
      "Heat water until it is gently simmering.",
      "Cut the dough ropes into pieces about 1 cm thick.",
      "Drop the pieces directly into the simmering water.",
      "Remove the noodles with a ladle once they float to the surface.",
      "Serve with green pesto, parmesan, and basil leaves.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Basil Pesto Pasta",
    description: "Fresh basil pesto blended with garlic, olive oil, and toasted pine nuts. Finished with parmesan for a creamy, savory bite. Toss over hot pasta for a simple classic.",
    imageUrl: "/images/basilikum_pesto.jpg",
    tags: ["Vegetarian", "Pasta"],
    ingredients: [
      "50 g fresh basil",
      "50 g parmesan, grated",
      "40 g pine nuts",
      "2 garlic cloves",
      "150 ml olive oil",
      "Pasta of choice",
    ],
    steps: [
      "Cook the pasta according to the package instructions.",
      "Toast the pine nuts in a dry pan until fragrant.",
      "Transfer the pine nuts to a plate to cool.",
      "Peel the garlic and cut it into smaller pieces.",
      "Add basil, garlic, and olive oil to a tall container.",
      "Blend until smooth with an immersion blender.",
      "Add the pine nuts and a pinch of salt.",
      "Add more olive oil if needed for the desired consistency.",
      "Stir in the parmesan once the pesto is creamy.",
      "Serve the pesto over the cooked pasta.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Asparagus Tomato Pasta",
    description: "Spring pasta with green asparagus, tomatoes, basil, and lemon. A light pan sauce is built with broth and white wine and finished with parmesan. Fresh, bright, and aromatic.",
    imageUrl: "/images/pasta_spargel.jpg",
    tags: ["Vegetarian", "Pasta"],
    ingredients: [
      "2 shallots",
      "2 garlic cloves",
      "1 organic lemon",
      "500 g green asparagus",
      "3 tomatoes",
      "White wine",
      "0.5 bunch fresh basil",
      "500 g pasta",
      "Salt",
      "1 tbsp olive oil",
      "100 ml vegetable broth",
      "50 g grated parmesan",
      "White pepper",
    ],
    steps: [
      "Peel the shallots and garlic.",
      "Dice the shallots and finely chop the garlic.",
      "Wash the lemon, finely grate the zest, and squeeze the juice.",
      "Wash the green asparagus.",
      "Peel the lower third of the asparagus and trim off the woody ends.",
      "Cut the asparagus diagonally into pieces about 4 cm long.",
      "Wash the tomatoes and cut them into small cubes.",
      "Rinse and chop the basil, reserving a few leaves for garnish.",
      "Cook the pasta in salted water according to the package instructions.",
      "Heat olive oil in a pan.",
      "Fry the asparagus until lightly browned.",
      "Remove the asparagus from the pan and set aside.",
      "Sauté shallots and garlic in the same pan for 2–3 minutes.",
      "Deglaze with vegetable broth and white wine.",
      "Simmer for 5 minutes, adding pasta water as needed.",
      "Drain the pasta.",
      "Add pasta and diced tomatoes to the pan.",
      "Add the asparagus back to the pan and mix well.",
      "Mix parmesan with lemon zest and chopped basil.",
      "Stir parmesan mixture and lemon juice into the pasta.",
      "Season with white pepper and a little salt to taste.",
      "Serve with reserved basil leaves.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Pesto Pasta Bake",
    description: "A creamy pasta bake with sun-dried tomato pesto, blistered cherry tomatoes, and melted mozzarella. The sauce is finished with cream and parmesan, then baked until golden. Great for an easy oven dinner.",
    imageUrl: "/images/rigatoni_pesto_auflauf.jpg",
    tags: ["Pasta", "Vegetarian"],
    ingredients: [
      "400 g pasta",
      "10 cherry tomatoes",
      "180 g sun-dried tomatoes in oil",
      "1 garlic clove",
      "80 g cashews",
      "50 ml olive oil",
      "1 tbsp lemon juice",
      "1 tbsp balsamic vinegar",
      "1 tsp honey",
      "100 ml whipping cream",
      "150 g parmesan, grated",
      "150 g mozzarella",
      "Salt",
      "Pepper",
      "Vegetable oil, for frying",
      "Basil, for serving",
    ],
    steps: [
      "Bring a large pot of salted water to a boil.",
      "Cook the rigatoni but drain a few minutes early so it is not fully al dente.",
      "Preheat the oven to 175°C.",
      "Halve the cherry tomatoes.",
      "Blend sun-dried tomatoes, garlic, cashews, olive oil, and lemon juice into a creamy pesto.",
      "Season the pesto with salt and pepper.",
      "Heat vegetable oil in a pan.",
      "Fry the cherry tomatoes with balsamic vinegar and honey for 3 minutes.",
      "Add the pesto and whipping cream to the pan.",
      "Mix well and simmer for 3–4 minutes.",
      "Add the pre-cooked rigatoni to the pan.",
      "Toss until everything is well coated.",
      "Transfer the mixture to a baking dish.",
      "Top with grated parmesan and mozzarella.",
      "Bake for about 15 minutes until the cheese is golden.",
      "Sprinkle with fresh basil before serving.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Coconut Shrimp Pasta",
    description: "Creamy curry-coconut pasta with shrimp, lemongrass, and a spiced blended sauce. The broth and coconut milk simmer with aromatics to build depth. Add shrimp back at the end and serve hot.",
    imageUrl: "/images/nudeln_kokos_sauce.jpg",
    tags: ["Pasta", "Seafood"],
    ingredients: [
      "125 g onion",
      "3 garlic cloves",
      "1 red chili, finely chopped",
      "2 tbsp tomato paste",
      "1 stalk lemongrass",
      "1 tbsp fresh ginger, finely chopped",
      "2 tsp Thai masala",
      "125 ml broth",
      "125 ml coconut milk",
      "Fresh herbs (basil, cilantro, lemon balm)",
      "Potato starch, for thickening",
      "Salt",
      "Pepper",
      "Curry",
      "8 tbsp peanut oil",
    ],
    steps: [
      "Cook the pasta according to the package instructions.",
      "Peel and finely chop the onion and garlic.",
      "Halve the lemongrass lengthwise and bend it several times.",
      "Heat oil in a pan and fry the shrimp briefly.",
      "Remove the shrimp from the pan and set aside.",
      "Add onion, garlic, and chili to a pot with 4 tbsp peanut oil.",
      "Add tomato paste and sauté briefly.",
      "Add lemongrass, ginger, and Thai masala.",
      "Sauté until fragrant.",
      "Pour in broth and coconut milk.",
      "Simmer for about 20 minutes.",
      "Remove the lemongrass.",
      "Blend the sauce with the remaining 4 tbsp peanut oil until smooth.",
      "Season with salt, pepper, and curry to taste.",
      "Stir in chopped fresh herbs.",
      "Thicken with potato starch if needed.",
      "Add the shrimp back into the sauce before serving.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Butter Chicken",
    description: "Butter chicken with tender roasted chicken served in a rich tomato curry sauce. The chicken is marinated in two stages, then baked and finished in a buttery, spiced sauce. Cream and cashews help create a smooth, velvety texture.",
    imageUrl: "/images/butter_chicken.jpg",
    tags: ["Indian", "Rice"],
    ingredients: [
      "1.5 to 2 pounds chicken breast",
      "2 tbsp freshly squeezed lemon juice",
      "3 tsp Kashmiri chili powder",
      "1 tsp kosher salt",
      "1/3 cup Greek yogurt",
      "2 tbsp avocado oil",
      "1 tsp ground fenugreek (leaves preferred)",
      "2 tsp turmeric powder",
      "3 tbsp chopped garlic",
      "1 tbsp chopped ginger",
      "2 tsp garam masala",
      "24 oz tomatoes (any kind)",
      "1 cinnamon stick",
      "1 green chili",
      "6 cardamom pods",
      "3 small pieces clove",
      "5 tbsp unsalted butter (3 tbsp at the start, 2 tbsp to finish)",
      "30 cashews",
      "2 tsp Kashmiri chili powder",
      "1 tsp sugar",
      "2 cups water",
      "1 tsp garam masala",
      "1/4 cup cream",
      "1 tsp fenugreek seeds (leaves preferred)",
      "1-2 tsp salt",
    ],
    steps: [
      "Cut the chicken breast into pieces.",
      "Mix lemon juice, Kashmiri chili powder, and kosher salt.",
      "Coat the chicken with the first marinade.",
      "Let the chicken rest briefly in the marinade.",
      "Mix Greek yogurt and avocado oil.",
      "Add fenugreek, turmeric, garlic, ginger, and garam masala to the yogurt mixture.",
      "Coat the chicken with the second marinade.",
      "Preheat the oven.",
      "Bake the marinated chicken until cooked through.",
      "Add tomatoes, cinnamon stick, green chili, cardamom, and cloves to a pot.",
      "Add water and simmer to build the sauce base.",
      "Add cashews and simmer until softened.",
      "Blend the sauce until smooth.",
      "Return the sauce to the pot.",
      "Add butter, Kashmiri chili powder, sugar, and garam masala.",
      "Simmer gently and season with salt.",
      "Stir in cream to finish the sauce.",
      "Add the baked chicken to the sauce and heat through before serving.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },


];

const normalizeTitle = (title: string) => title.trim().toLowerCase();


export async function seedDatabase() {
  try {
    const existing = await db.select({ title: recipes.title }).from(recipes);
    const existingTitles = new Set(existing.map((recipe) => normalizeTitle(recipe.title)));

    let inserted = 0;
    let skipped = 0;

    for (const recipe of seedRecipes) {
      if (existingTitles.has(normalizeTitle(recipe.title))) {
        skipped += 1;
        continue;
      }

      await db.insert(recipes).values(recipe);
      existingTitles.add(normalizeTitle(recipe.title));
      inserted += 1;
    }

    log(`Seed finished: inserted ${inserted}, skipped ${skipped}`);
  } catch (err) {
    log(`Seed error: ${err}`);
  }
}