import { db } from "./db";
import { recipes } from "@shared/schema";
import { log } from "./index";

const seedRecipes = [
  {
    title: "Classic Pasta Carbonara",
    description: "A rich and creamy Italian classic made with just a few simple ingredients. The key is tempering the eggs with the hot pasta water.",
    imageUrl: "/images/carbonara.png",
    tags: ["Italian", "Pasta", "Quick"],
    ingredients: [
      "400g spaghetti",
      "200g pancetta or guanciale, diced",
      "4 large egg yolks",
      "100g Pecorino Romano, finely grated",
      "Freshly ground black pepper",
      "Salt for pasta water",
    ],
    steps: [
      "Bring a large pot of salted water to a boil and cook spaghetti until al dente",
      "While pasta cooks, fry pancetta in a large skillet over medium heat until crispy",
      "Whisk together egg yolks and grated Pecorino in a bowl",
      "Reserve 1 cup of pasta water, then drain the spaghetti",
      "Add hot pasta to the pancetta skillet, remove from heat",
      "Pour egg mixture over pasta, tossing quickly to create a creamy sauce",
      "Add pasta water a splash at a time if needed for consistency",
      "Serve immediately with extra Pecorino and black pepper",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Bolognese",
    description: "A slow-simmered Italian meat sauce made with minced meat, vegetables, wine, and tomatoes. The flavors develop through gentle cooking until rich and thick. Serve with pasta and finish with grated parmesan.",
    imageUrl: "/images/bolognese.jpg",
    tags: ["Italian", "Pasta"],
    ingredients: [
      "Butter",
      "Olive oil",
      "Basil",
      "Onions",
      "Carrot",
      "Celery",
      "Garlic",
      "Minced meat",
      "Red wine",
      "Peeled tomatoes",
      "Linguine",
      "Parmesan",
    ],
    steps: [
      "Brown the minced meat in a large pan over high heat until fully browned.",
      "Add onions, carrot, celery, and garlic to the pan.",
      "Cook until the vegetables become soft.",
      "Deglaze with a splash of red wine.",
      "Simmer until the wine is slightly reduced.",
      "Add the peeled tomatoes.",
      "Season with salt, pepper, and basil.",
      "Simmer on low heat for 30–45 minutes until thick and rich.",
      "Cook the linguine according to the package instructions.",
      "Mix the sauce with the cooked pasta.",
      "Sprinkle with parmesan before serving.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Hawaiian Poke Bowl",
    description: "A vibrant and healthy bowl packed with fresh flavors. This Hawaiian staple is perfect for a light yet satisfying meal.",
    imageUrl: "/images/poke-bowl.png",
    tags: ["Hawaiian", "Healthy", "Seafood"],
    ingredients: [
      "300g sushi-grade ahi tuna, cubed",
      "2 cups cooked sushi rice",
      "1 ripe avocado, sliced",
      "1/2 cup shelled edamame",
      "1/4 cup soy sauce",
      "1 tsp sesame oil",
      "1 mango, diced",
      "Sesame seeds and scallions for garnish",
      "Pickled ginger (optional)",
    ],
    steps: [
      "Marinate tuna cubes in soy sauce and sesame oil for 15 minutes",
      "Cook sushi rice according to package directions and let cool slightly",
      "Divide rice between two bowls",
      "Arrange marinated tuna, avocado, edamame, and mango on top",
      "Sprinkle with sesame seeds and sliced scallions",
      "Serve with pickled ginger on the side",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Fluffy Blueberry Pancakes",
    description: "Golden, pillowy pancakes bursting with fresh blueberries. A perfect weekend breakfast that the whole family will love.",
    imageUrl: "/images/pancakes.png",
    tags: ["Breakfast", "Sweet", "Family"],
    ingredients: [
      "1 1/2 cups all-purpose flour",
      "3 1/2 tsp baking powder",
      "1 tbsp sugar",
      "1/4 tsp salt",
      "1 1/4 cups milk",
      "1 egg",
      "3 tbsp melted butter",
      "1 cup fresh blueberries",
      "Maple syrup for serving",
    ],
    steps: [
      "Whisk together flour, baking powder, sugar, and salt in a large bowl",
      "Make a well in the center and pour in milk, egg, and melted butter",
      "Mix until smooth but don't overmix - a few lumps are fine",
      "Gently fold in fresh blueberries",
      "Heat a lightly oiled griddle or pan over medium-high heat",
      "Pour about 1/4 cup batter per pancake onto the griddle",
      "Cook until bubbles form on the surface, then flip and cook until golden",
      "Stack pancakes and serve with butter and warm maple syrup",
    ],
    createdByUserId: "seed",
    isBase: true,
  },

    {
    title: "Pizza",
    description: "A simple homemade pizza dough made in a mixer and left to rise for 2 hours. The amount is intended for 6 people. Top with tomato sauce, mozzarella, and parmesan and bake until golden.",
    imageUrl: "/images/pizza.jpg",
    tags: ["Italian"],
    ingredients: [
      "600g flour",
      "300ml water",
      "Olive oil",
      "Yeast",
      "Salt",
      "Sugar",
      "Tomato sauce",
      "Mozzarella",
      "Parmesan",
    ],
    steps: [
      "Make the dough in a mixer.",
      "Let the dough rise for 2 hours.",
      "Shape the dough into pizza bases.",
      "Spread tomato sauce over the bases.",
      "Top with mozzarella and parmesan.",
      "Bake until the crust is cooked and lightly browned.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Mushroom Ragout",
    description: "A hearty mushroom ragout thickened with tomatoes and enriched with toasted walnuts. Dried porcini add depth, while herbs bring a savory aroma. Toss with pasta and finish with fresh parsley.",
    imageUrl: "/images/pilz-ragout.jpg",
    tags: ["Vegetarian", "Pasta"],
    ingredients: [
      "1 can chopped tomatoes",
      "400 g button mushrooms",
      "100 g walnuts",
      "20 g porcini, dried",
      "Pasta",
      "2 celery stalks",
      "2 garlic cloves",
      "1 onion",
      "1 handful fresh parsley",
      "2 tbsp tamari",
      "1 tbsp tomato paste",
      "1 tsp thyme, dried",
      "1 tsp oregano, dried",
      "1 tsp rosemary",
      "Salt",
      "Pepper",
      "Olive oil",
    ],
    steps: [
      "Pour 250 ml boiling water over the dried porcini and soak for 20 minutes.",
      "Drain the porcini, reserving the soaking liquid.",
      "Chop the soaked porcini into small pieces.",
      "Finely chop the walnuts until they resemble coarse breadcrumbs.",
      "Toast the walnuts in a large deep pan over medium heat for about 5 minutes, stirring occasionally.",
      "Remove the toasted walnuts from the pan and set aside.",
      "Add onion, garlic, and celery to the pan with olive oil and a pinch of salt.",
      "Fry for 5–10 minutes until softened.",
      "Add fresh mushrooms and diced pepper, then add thyme, oregano, and rosemary.",
      "Cook for about 5 minutes until softened.",
      "Add the canned tomatoes and tomato paste to the pan.",
      "Add the tamari, the soaked porcini, and the reserved soaking liquid.",
      "Simmer for 10–15 minutes until the ragout thickens and excess liquid cooks off.",
      "Stir in the toasted walnuts and nutritional yeast.",
      "Simmer for 5 more minutes.",
      "Cook the pasta in boiling salted water according to the package instructions.",
      "Drain the pasta well.",
      "Stir the pasta into the finished ragout.",
      "Sprinkle with chopped parsley before serving.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Spinach Pasta",
    description: "Creamy pasta with sun-dried tomatoes, parmesan, and baby spinach. The sauce comes together quickly with cream and vegetable stock. A fast vegetarian meal for busy days.",
    imageUrl: "/images/Pasta_Spinat-Sahne-Sauce.jpg",
    tags: ["Pasta", "Vegetarian"],
    ingredients: [
      "300 g pasta",
      "1 onion",
      "2 garlic cloves",
      "1 tbsp olive oil",
      "100 g sun-dried tomatoes (from a jar)",
      "250 g cooking cream",
      "200 ml vegetable stock",
      "60 g grated parmesan",
      "100 g baby spinach",
      "Salt and pepper",
      "1 tsp Italian herbs",
    ],
    steps: [
      "Cook the pasta according to the package instructions.",
      "Finely chop the onion and garlic.",
      "Heat olive oil in a pan.",
      "Fry the onion and garlic for 2 minutes.",
      "Add the cream and vegetable stock.",
      "Bring the sauce to a boil.",
      "Stir in the parmesan, sun-dried tomatoes, and baby spinach.",
      "Simmer for 5 minutes over medium heat.",
      "Season with salt, pepper, and Italian herbs.",
      "Stir the cooked pasta into the sauce.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Penne Arrabbiata",
    description: "Spicy Italian penne in a simple tomato sauce with garlic, chili, and herbs. The sauce simmers until rich and aromatic. Finish with parmesan if you like.",
    imageUrl: "/images/penne_arrabiata.jpg",
    tags: ["Pasta", "Italian", "Spicy"],
    ingredients: [
      "400 g penne",
      "1 can tomatoes",
      "2 tbsp olive oil",
      "4 garlic cloves",
      "1 bunch basil",
      "3 red chili peppers",
      "1 pinch pepper",
      "1 pinch salt",
      "1 sprig oregano",
      "Parmesan",
    ],
    steps: [
      "Cook the penne in salted water until al dente.",
      "Drain the pasta and let it drip off well.",
      "Peel and finely chop the garlic.",
      "Wash the basil, drain it, and finely chop it.",
      "Wash the chili peppers, remove the seeds, and chop them.",
      "Gently sauté garlic and chili in a pan with olive oil.",
      "Add the tomatoes to the pan.",
      "Simmer the sauce for 15 minutes.",
      "Add a little pasta water to the sauce.",
      "Add the drained penne to the pan.",
      "Stir in basil and oregano.",
      "Season with salt and pepper to taste.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Mozzarella Pasta",
    description: "Pasta tossed with a fresh tomato sauce, herbs, and melty mozzarella. A splash of white wine adds brightness to the sauce. Finish with fresh basil for a classic Italian feel.",
    imageUrl: "/images/mozzarella-tomatensauce.jpg",
    tags: ["Pasta", "Italian", "Vegetarian"],
    ingredients: [
      "350 g pasta",
      "Bunch fresh basil",
      "250 g mozzarella",
      "3 tbsp olive oil",
      "2 tsp sugar",
      "1 tsp dried oregano",
      "1 splash white wine",
      "1 pinch salt",
      "1 pinch pepper",
      "1 tbsp oil for the pan",
      "500 g passata",
      "250 g cherry tomatoes",
    ],
    steps: [
      "Cook the pasta in salted water until al dente.",
      "Peel and finely chop the onion and garlic.",
      "Heat oil in a pan and sauté the onion and garlic.",
      "Wash the cherry tomatoes and remove the seeds.",
      "Dice the tomatoes very finely.",
      "Add the diced tomatoes to the pan and sauté briefly.",
      "Deglaze with a splash of white wine.",
      "Pour in the passata.",
      "Season with salt, pepper, sugar, olive oil, and oregano.",
      "Let the sauce simmer briefly.",
      "Cut the mozzarella into small pieces.",
      "Mix pasta, mozzarella, basil leaves, and tomato sauce together.",
      "Serve immediately.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Baked Feta Pasta",
    description: "Oven-baked feta and tomatoes turn into a creamy sauce with almost no effort. Herbs and garlic add a savory kick as everything roasts together. Toss with pasta and serve hot with parsley.",
    imageUrl: "/images/feta-pasta.jpg",
    tags: ["Pasta", "Vegetarian"],
    ingredients: [
      "300 g feta",
      "700 g cherry tomatoes",
      "2 garlic cloves",
      "1 tbsp olive oil",
      "0.5 bunch parsley",
      "1 tsp dried thyme",
      "500 g pasta",
      "Salt",
      "Pepper",
    ],
    steps: [
      "Preheat the oven to 200°C top/bottom heat.",
      "Add tomatoes and garlic to a large baking dish.",
      "Add half of the parsley and mix everything together.",
      "Place the feta in the center of the baking dish.",
      "Sprinkle the remaining thyme over the feta.",
      "Season with salt and pepper.",
      "Drizzle with olive oil.",
      "Bake for about 30 minutes.",
      "Cook the pasta al dente according to the package instructions.",
      "Remove the baking dish from the oven.",
      "Mix the baked feta with the tomatoes until creamy.",
      "Drain the pasta.",
      "Add the pasta to the sauce and mix well.",
      "Garnish with the remaining parsley and serve hot.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Pepper Pasta",
    description: "Creamy pasta sauce made from roasted red peppers blended smooth with garlic and onion. Roasting adds sweetness and depth while keeping the recipe simple. Toss with pasta and finish with parmesan.",
    imageUrl: "/images/paprikasauce.jpg",
    tags: ["Vegetarian", "Pasta"],
    ingredients: [
      "250 g pasta of choice",
      "1 onion",
      "3-4 garlic cloves",
      "2 red peppers",
      "1 tbsp oil",
      "2 tbsp tomato paste",
      "3-4 tbsp parmesan",
      "⅔ tsp salt",
      "Hot paprika powder, pepper, or chili to taste",
    ],
    steps: [
      "Preheat the oven to 220°C top/bottom heat.",
      "Peel the onion and garlic.",
      "Quarter the onion and leave the garlic whole.",
      "Halve the peppers, remove seeds, wash, and cut into strips.",
      "Place peppers, onion, and garlic on a baking tray.",
      "Drizzle with oil.",
      "Roast for about 20 minutes.",
      "Cook the pasta al dente and drain.",
      "Blend the roasted vegetables with tomato paste and salt until creamy.",
      "Season with hot paprika powder, pepper, or chili.",
      "Bring the pepper sauce to a brief boil in a pot.",
      "Adjust seasoning and thin with water if needed.",
      "Add the pasta to the sauce and mix well.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Mushroom Pasta",
    description: "Creamy mushroom pasta with garlic, onions, and a quick pan sauce. A splash of white wine is optional but adds extra aroma. Serve with parmesan and fresh herbs.",
    imageUrl: "/images/pilzsahne.jpg",
    tags: ["Vegetarian", "Pasta"],
    ingredients: [
      "300 g pasta",
      "2 tbsp rapeseed oil or olive oil",
      "1 onion, chopped",
      "4 garlic cloves, chopped",
      "500 g button mushrooms, sliced",
      "80 ml dry white wine (optional)",
      "360 ml vegetable stock",
      "3 tbsp flour",
      "Salt and pepper to taste",
    ],
    steps: [
      "Cook the pasta al dente in salted water according to the package instructions.",
      "Drain the pasta.",
      "Heat 1 tbsp oil in a pan.",
      "Fry the onion for about 3 minutes.",
      "Add the remaining oil, garlic, and mushrooms.",
      "Fry for 5–7 minutes until the mushrooms are browned.",
      "Deglaze with white wine if using.",
      "Let the wine evaporate briefly.",
      "Mix vegetable stock, cream, and flour together.",
      "Pour the mixture into the pan.",
      "Simmer for 5–10 minutes until the sauce reaches the desired thickness.",
      "Season with paprika powder, salt, and pepper.",
      "Stir the pasta into the sauce.",
      "Serve with parmesan and fresh herbs.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Zucchini Ricotta Pasta",
    description: "A creamy pasta dish where zucchini is gently cooked and mixed into a ricotta cheese cream. Parmesan, pecorino, and nutmeg add richness and depth. Toss with pasta and brighten with a little lemon.",
    imageUrl: "/images/zucchini_ricotta_pasta.jpg",
    tags: ["Pasta", "Vegetarian"],
    ingredients: [
      "400 g fusilli or another short pasta shape",
      "400 g zucchini",
      "100 g ricotta",
      "25 g pecorino",
      "25 g parmesan",
      "1/2 tsp nutmeg",
      "4 tbsp olive oil",
      "2 garlic cloves",
      "10 basil leaves",
      "Salt",
      "Freshly ground black pepper",
      "Lemon",
    ],
    steps: [
      "Cook the pasta in salted water according to the package instructions.",
      "Dice the zucchini.",
      "Roughly chop the basil.",
      "Finely chop the garlic.",
      "Heat olive oil in a pan and warm the garlic briefly.",
      "Add zucchini and basil to the pan.",
      "Season with salt.",
      "Cover and cook on low heat for 15–20 minutes, stirring occasionally.",
      "Add a little warm water if the zucchini starts to stick.",
      "Mash the cooked zucchini.",
      "Stir the ricotta in a large bowl until creamy.",
      "Mix in parmesan, pecorino, and nutmeg.",
      "Add the mashed zucchini to the bowl.",
      "Add 3–4 tbsp pasta water and mix well.",
      "Add the hot drained pasta to the cream and mix thoroughly.",
      "Season with salt and black pepper to taste.",
      "Serve and add lemon as desired.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },
  {
    title: "Lemon Zoodles Pasta",
    description: "A bright lemon pasta mixed with quickly sautéed zucchini noodles and a creamy cashew-lemon sauce. Basil and garlic add freshness and aroma. A satisfying vegetarian dish with a light, zesty finish.",
    imageUrl: "/images/lemon_zoodles_pasta.jpg",
    tags: ["Pasta", "Vegetarian"],
    ingredients: [
      "3 tbsp cashews",
      "200 ml water",
      "250 g spaghetti",
      "2 tbsp and 1/2 tsp salt",
      "4 garlic cloves",
      "2 zucchini",
      "1 untreated organic lemon",
      "Black pepper",
      "about 30 basil leaves",
      "2 tbsp nutritional yeast",
      "about 200 g cooked white beans",
      "3 tbsp olive oil",
      "Dried chili (optional)",
    ],
    steps: [
      "Soak the cashews in hot water.",
      "Cook the spaghetti al dente in salted water.",
      "Finely chop the garlic.",
      "Spiralize the zucchini into zoodles and shorten them if needed.",
      "Grate the lemon zest and squeeze the lemon juice.",
      "Blend lemon zest and juice with cashews, water, salt, pepper, basil, nutritional yeast, and white beans until creamy.",
      "Heat olive oil in a pan.",
      "Briefly fry dried chili and garlic.",
      "Add the zoodles and sauté very briefly.",
      "Add the spaghetti to the pan.",
      "Add the lemon-cashew sauce and mix everything together.",
      "Garnish with lemon zest and basil and serve.",
    ],
    createdByUserId: "seed",
    isBase: true,
  },

];

const normalizeTitle = (title: string) => title.trim().toLowerCase();


export async function seedDatabase() {
  try {
    const existing = await db.select({ title: recipes.title }).from(recipes);
    const existingTitles = new Set(existing.map((recipe) => normalizeTitle(recipe.title)));

    let inserted = 0;
    let skipped = 0;

    for (const recipe of seedRecipes) {
      if (existingTitles.has(normalizeTitle(recipe.title))) {
        skipped += 1;
        continue;
      }

      await db.insert(recipes).values(recipe);
      existingTitles.add(normalizeTitle(recipe.title));
      inserted += 1;
    }

    log(`Seed finished: inserted ${inserted}, skipped ${skipped}`);
  } catch (err) {
    log(`Seed error: ${err}`);
  }
}